### ISSUE TITLE
Do you plan an update for DaisyUI 4x?

### ISSUE THREAD

**Issue by aaronlippold** [OSSPhilippines/nuxtwind-daisy#5]

**Comment by jofftiquez** [comment]
Hi @aaronlippold yes! Definitely, thanks for the reminder

**Comment by aaronlippold** [comment]
Great to hear, I plan to use this on my next project within the next week or two when we get started

**Comment by jofftiquez** [comment]
@aaronlippold upon checking there's already an existing PR, I'll be checking it today. 

https://github.com/OSSPhilippines/nuxtwind-daisy/pull/6

**Comment by jofftiquez** [comment]
Hi, it's updated now @aaronlippold closing this now. Thank you!

**Comment by aaronlippold** [comment]
Very cool, don't forget to update the site landing page to the V4 as well, don't want to confuse end users
